const RegQQConfig = {
  serverBaseURL: "https://www.qq123qq.com/api",
  cacheToolBaseURL: "http://127.0.0.1:9091",
  cacheToolPackageName: "com.extracache.cachetool",
  cacheToolAppName: "CacheTool",
  cacheToolLaunchTimeoutMs: 45000,
  cacheToolStatusRetryIntervalMs: 1000,
  qqPackageName: "com.tencent.mobileqq",
  qqAppName: "QQ",
  clearQQDataBeforeLaunch: true,
  clearQQDataDelayMs: 500,
  taskPollIntervalMs: 2000,
  taskErrorRetryIntervalMs: 5000,
  heartbeatIntervalMs: 30000,
  cacheUploadTimeoutMs: 60000,
  resetAfterSuccess: true,
  resetEnvironment: {
    hardModify: {
      enabled: true,
      startupGuardEnabled: true,
      startupRetryIntervalMs: 10 * 1000,
      startupAllowBackupAfterMs: 60 * 1000,
      enableWifiBeforeTrigger: true,
      enableUsbDebugBeforeTrigger: true,
      useDeviceIdAsWifiSSID: false,
      wifiSSID: "ddddffff",
      wifiPassword: "1234567890",
      wifiConnectTimeoutMs: 60 * 1000,
      hostIPFile: "/sdcard/ip.txt",
      backupHostIPFile: "/sdcard/ip.txt.bak",
      serverPort: 8088,
      healthPath: "/devices/",
      triggerPath: "/硬改自动化/",
      requestTimeoutMs: 1000 * 60 * 10,
      responseWarnMs: 5000,
      beforeTriggerSleepMs: 1000,
      afterTriggerSleepMs: 3000,
    },
  },
  exceptionFlow: {
    defaultRetryLimit: 0,
    retryIntervalMs: 1000,
    reportStageException: true,
    resetOnFailure: true,
    stageRetryLimits: {
      open_register_page: 0,
      handle_authorize_dialog: 0,
      input_phone: 0,
      security_verify: 0,
      wait_or_submit_verify_code: 0,
      complete_profile: 0,
      wait_login_success: 0,
      submit_cache: 0,
      reset_environment: 0,
    },
  },
  imageVerify: {
    endpoint: "http://gpu1.xinyuocr.xyz:8889/api/qrcode/predict",
    username: "",
    password: "",
    modelName: "普通模型",
    keyCode: "",
    requestId: "42077360",
    version: "3.1.1",
    question: "框出正确位置",
    system: "",
    pressDurationMs: 50,
    clickIntervalMs: 300,
    screenshotDir: files.cwd() + "/capture",
  },
  dev: {
    // worker | once | upload_cache | image_verify | custom
    entry: "worker",
    uploadCacheQQPwd: "",
    imageVerifyQuestion: "框出正确位置",
    mockTask: {
      id: "local-dev-task",
      phone: "18819351383",
      smsReceiveMode: "USER_SENT_TO_TX", // USER_SENT_TO_TX | PLATFORM_SEND
    },
  },
};

module.exports = {
  RegQQConfig,
};
